/** react-query anahtarlari tek yerde: gecersiz kilma (invalidate) tutarli olsun */
export const qk = {
  settings: ['settings'] as const,
  categories: ['categories'] as const,
  products: ['products'] as const,
  menuFull: ['menu-full'] as const,
  optionGroups: ['option-groups'] as const,
  areas: ['areas'] as const,
  tables: ['tables'] as const,
  openOrders: ['orders', 'open'] as const,
  order: (id: string) => ['order', id] as const,
  orderItems: (orderId: string) => ['order-items', orderId] as const,
  kitchen: ['kitchen'] as const,
  ingredients: ['ingredients'] as const,
  ingredientStock: ['ingredient-stock'] as const,
  recipe: (productId: string) => ['recipe', productId] as const,
  optionRecipe: (optionId: string) => ['option-recipe', optionId] as const,
  purchases: ['purchases'] as const,
  waste: ['waste'] as const,
  activeCount: ['stock-count', 'active'] as const,
  countItems: (countId: string) => ['stock-count-items', countId] as const,
  stockReport: (from: string, to: string) => ['stock-report', from, to] as const,
  dailySummary: (from: string, to: string) => ['daily-summary', from, to] as const,
  productSales: (from: string, to: string) => ['product-sales', from, to] as const,
  hourlyLoad: (from: string, to: string) => ['hourly-load', from, to] as const,
  productCosts: ['product-costs'] as const,
} as const;
